name: Codigician CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Buid application jar
      run: mvn package
    - name: Upload application fat jar artifact
      uses: actions/upload-artifact@v2
      with:
        name: fat-jar
        path: target/*.jar

  package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download fat jar
      uses: actions/download-artifact@v2
      with:
        name: fat-jar
    - name: Build docker container
      run: docker build . --tag codigician-api:$(date +%s)
    needs: [build]

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Running unit tests
        run: mvn -B test --file pom.xml
    needs: [build]

  staging-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download fat jar
      uses: actions/download-artifact@v2
      with:
        name: fat-jar
    - name: Deploy to Heroku
      uses: gonuit/heroku-docker-deploy@v1.3.3
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        email: ${{secrets.HEROKU_EMAIL}}
        heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
        dockerfile_name: Dockerfile
        dockerfile_directory: ./
        docker_options: "--no-cache"
        process_type: web
    needs: [build]