name: Codigician CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Buid application jar
      run: mvn package
    - name: List directories
      run: ls

  list:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: List directories
      run: ls -la
    needs: [build]

  package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker container
      run: docker build . --tag codigician-api:$(date +%s)
    needs: [list]
    #  staging-deploy:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: Deploy to Heroku
#      uses: AkhileshNS/heroku-deploy@v3.12.12
#      with:
#        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#        heroku_email: ${{secrets.HEROKU_EMAIL}}
#        heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
